version: "3.3"

services:
  graphqlapi:
    image: fan-app/graphqlapi:${TAG:-latest}
    container_name: graphql
    build:
      context: ./services/graphqlapi
      dockerfile: Dockerfile
    environment:
      - GRAPHQL_ENV=production
      - REDIS_HOST=redis
    ports:
      - "4200:4200"

  base-knex-redis:
    image: fan-app/base-knex-redis:${TAG:-latest}
    container_name: base-knex-redis
    build:
      context: ./services/base-knex-redis
      dockerfile: Dockerfile
    env_file: ./services/base-knex-redis/.env
    ports:
      - "4201:3000"
    depends_on:
      - base-knex-redis-db
      - redis

  base-knex-redis-db:
    image: postgres:12.0
    container_name: base-knex-redis-db
    ports:
      - "6001:5432"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file: ./services/base-knex-redis/.env
    volumes:
      - ./services/base-knex-redis/postgres_data:/var/lib/postgresql/data/pgdata

  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./services/base-knex-redis/redis.conf:/opt/bitnami/redis/etc/redis.conf
      - ./services/base-knex-redis/redis_data:/bitnami/redis/data

volumes:
  base-knex-redis-db:
  redis:
